services:
  opencode:
    cpuset: "${OPENCODE_CPUSET:-2-3}"
    #image: ghcr.io/anomalyco/opencode:1.14.47
    #image: ${OPENCODE_IMAGE_URL:-devsnowdon/opencode-docker}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        OPENCODE_IMAGE_URL: ${OPENCODE_IMAGE_URL:-devsnowdon/opencode-docker:latest}
        PROJECT_WORKSPACE: ${WORKSPACE:-${SD_OPENCODE}}
    # restart: unless-stopped
    entrypoint: ["/bin/sh", "-c"]
    command:
      - "sleep 999999999d"
    labels:
      - "dev.snowdon.opencode.managed=true"
      - "dev.snowdon.opencode.workspace=${WORKSPACE}"
    volumes:
      - ${WORKSPACE:-${SD_OPENCODE}}:/workspace
      - /etc/localtime:/etc/localtime:ro

      # opencode
      - ${OPENCODE_CACHE_DIR:-${HOME}/.cache/opencode/cache}:/home/other/.cache/opencode/cache
      - ${OPENCODE_DATA_DIR:-${HOME}/.local/share/opencode}:/home/other/.local/share/opencode
      - ${OPENCODE_CONFIG_DIR:-${HOME}/.config/opencode}:/home/other/.config
      - ./opencode/agent.md:/home/other/.config/opencode/AGENTS.md:ro
    ports:
      - "4096:4096"

  # only run as one off
  # TODO: smaller image
  tui:
    image: ${OPENCODE_IMAGE_URL:-devsnowdon/opencode-docker}
    stdin_open: true
    tty: true
    labels:
      - "dev.snowdon.opencode.managed=true"
      - "dev.snowdon.opencode.tui=true"
      - "dev.snowdon.opencode.workspace=${WORKSPACE}"
