alias opencode:update='( cd $SD_OPENCODE && docker compose pull )'
alias opencode='$SD_OPENCODE/scripts/launcher.sh start'
alias opencode:stop='$SD_OPENCODE/scripts/launcher.sh stop'
alias opencode:exec='$SD_OPENCODE/scripts/launcher.sh exec'
alias opencode:shell='$SD_OPENCODE/scripts/launcher.sh exec sh'
alias opencode:run='$SD_OPENCODE/scripts/launcher.sh run'
alias opencode:setup='$SD_OPENCODE/scripts/launcher.sh setup'
alias opencode:up='$SD_OPENCODE/scripts/launcher.sh up'
alias opencode:new='$SD_OPENCODE/scripts/launcher.sh new'
alias opencode:end='$SD_OPENCODE/scripts/launcher.sh end'
alias opencode:compose='$SD_OPENCODE/scripts/launcher.sh compose'
alias opencode:changes='$SD_OPENCODE/scripts/launcher.sh changes'
alias opencode:scaffold='$SD_OPENCODE/scripts/launcher.sh scaffold'
alias opencode:help='$SD_OPENCODE/scripts/launcher.sh help'
alias opencode:help:c='$SD_OPENCODE/scripts/launcher.sh help'
alias oc='opencode'
alias oc:s='opencode:stop';
alias oc:u='opencode:update';
alias oc:e='opencode:exec';
alias oc:sh='opencode:shell';
alias oc:r='opencode:run';
alias oc:setup='opencode:setup';
alias oc:n='opencode:new';
alias oc:e='opencode:end';
alias oc:up='opencode:up';
alias oc:c='opencode:compose';
alias oc:ch='opencode:changes';
alias oc:sf='opencode:scaffold';
alias oc:h='opencode:help';
