alias opencode:update='$SD_OPENCODE/scripts/launcher.sh update'
alias opencode='$SD_OPENCODE/scripts/launcher.sh start'
alias opencode:down='$SD_OPENCODE/scripts/launcher.sh down'
alias opencode:exec='$SD_OPENCODE/scripts/launcher.sh exec'
alias opencode:shell='$SD_OPENCODE/scripts/launcher.sh shell'
alias opencode:run='$SD_OPENCODE/scripts/launcher.sh run'
alias opencode:setup='$SD_OPENCODE/scripts/launcher.sh setup'
alias opencode:up='$SD_OPENCODE/scripts/launcher.sh up'
alias opencode:new='$SD_OPENCODE/scripts/launcher.sh new'
alias opencode:stop='$SD_OPENCODE/scripts/launcher.sh stop'
alias opencode:delete='$SD_OPENCODE/scripts/launcher.sh delete'
alias opencode:ls='$SD_OPENCODE/scripts/launcher.sh ls'
alias opencode:compose='$SD_OPENCODE/scripts/launcher.sh compose'
alias opencode:changes='$SD_OPENCODE/scripts/launcher.sh changes'
alias opencode:scaffold='$SD_OPENCODE/scripts/launcher.sh scaffold'
alias opencode:bg='$SD_OPENCODE/scripts/launcher.sh bg'
alias opencode:git='$SD_OPENCODE/scripts/launcher.sh git'
alias opencode:repl='$SD_OPENCODE/scripts/launcher.sh repl'
alias opencode:help='$SD_OPENCODE/scripts/launcher.sh help'
alias opencode:help:c='$SD_OPENCODE/scripts/launcher.sh help'
alias oc='opencode'
alias ocs='opencode:stop';
alias ocud='opencode:update';
alias ocsh='opencode:shell';
alias ocr='opencode:run';
alias ocsetup='opencode:setup';
alias ocn='opencode:new';
alias ocd='opencode:down';
alias ocdel='opencode:delete';
alias ocl='opencode:ls';
alias ocu='opencode:up';
alias occ='opencode:compose';
alias occh='opencode:changes';
alias ocsf='opencode:scaffold';
alias ocbg='opencode:bg';
alias och='opencode:help';
alias ocg='opencode:git';
