services:
  opencode:
    volumes:
      # rust
      - ${OPENCODE_CARGO_REGISTRY_DIR:-${HOME}/.cargo/registry}:/home/other/.cargo/registry
      - ${OPENCODE_CARGO_GIT_DIR:-${HOME}/.cargo/git}:/home/other/.cargo/git
      - ${OPENCODE_SCCACHE_DIR:-${HOME}/.cache/sccache}:/home/other/.cache/sccache
