name: Update Docker Hub Description
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - README.md
      - .github/workflows/dockerhub-description.yml
jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Update Docker Hub README
      uses: peter-evans/dockerhub-description@1b9a80c056b620d92cedb9d9b5a223409c68ddfa #v5.0.0
      with:
        username: ${{ secrets.DOCKERHUB_TOKEN_ADMIN }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        repository: devsnowdon/opencode-docker
        enable-url-completion: true
        readme-filepath: ./README.md
